import { useMemo, useState } from "react";
import { Search, Filter, MailOpen, CheckCircle2, Siren, X } from "lucide-react";
import { emails, type EmailItem } from "@/lib/dashboard-data";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Panel, PageHeading, StatusPill } from "./ui";

export function EmailQueue() {
 const [search,setSearch]=useState(""); const [status,setStatus]=useState("All"); const [selected,setSelected]=useState<EmailItem|null>(null); const [items,setItems]=useState(emails);
 const filtered=useMemo(()=>items.filter(e=>(status==="All"||e.status===status)&&(e.subject.toLowerCase().includes(search.toLowerCase())||e.customer.toLowerCase().includes(search.toLowerCase()))),[search,status,items]);
 const update=(next:EmailItem["status"])=>{if(!selected)return;setItems(v=>v.map(e=>e.id===selected.id?{...e,status:next}:e));setSelected({...selected,status:next});};
 return <><PageHeading title="Email Queue" description={`${filtered.length} customer conversations in the current view`} actions={<Button><MailOpen/>Compose response</Button>}/><div className="grid gap-3 xl:grid-cols-[1fr_360px]">
 <Panel title="Inbox" action={<span className="text-xs text-muted-foreground">Updated just now</span>}><div className="mb-4 flex flex-col gap-2 sm:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-2.5 size-4 text-muted-foreground"/><Input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search subject or customer" className="pl-9"/></div><Select value={status} onValueChange={setStatus}><SelectTrigger className="w-full sm:w-44"><Filter className="size-4"/><SelectValue/></SelectTrigger><SelectContent>{["All","Open","In Review","Escalated","Resolved (AI)"].map(s=><SelectItem key={s} value={s}>{s}</SelectItem>)}</SelectContent></Select></div>
 <div className="overflow-x-auto"><table className="w-full min-w-[760px] text-left text-sm"><thead><tr className="border-b border-border text-xs text-muted-foreground">{["ID","Customer & subject","Category","Priority","Status","Time"].map(h=><th key={h} className="pb-3 font-semibold">{h}</th>)}</tr></thead><tbody>{filtered.map(e=><tr key={e.id} onClick={()=>setSelected(e)} className="cursor-pointer border-b border-border/70 transition-colors hover:bg-accent/60"><td className="py-3 font-mono text-xs text-muted-foreground">{e.id}</td><td><p className="font-semibold">{e.subject}</p><p className="text-xs text-muted-foreground">{e.customer}</p></td><td>{e.category}</td><td><StatusPill tone={e.priority==="High"?"danger":e.priority==="Medium"?"warning":"neutral"}>{e.priority}</StatusPill></td><td><StatusPill tone={e.status==="Resolved (AI)"?"success":e.status==="Escalated"?"danger":e.status==="In Review"?"warning":"info"}>{e.status}</StatusPill></td><td>{e.received}</td></tr>)}</tbody></table>{filtered.length===0&&<div className="py-16 text-center"><p className="font-semibold">No emails found</p><p className="text-sm text-muted-foreground">Try another search or status.</p></div>}</div></Panel>
 <Panel title="Conversation detail" className="h-fit"><>{selected?<div><div className="flex items-start justify-between"><div><StatusPill tone={selected.priority==="High"?"danger":"warning"}>{selected.priority} priority</StatusPill><h3 className="mt-3 text-lg font-bold">{selected.subject}</h3><p className="text-sm text-muted-foreground">{selected.customer} · {selected.id}</p></div><Button variant="ghost" size="icon" onClick={()=>setSelected(null)} aria-label="Close details"><X/></Button></div><div className="my-5 rounded-md bg-muted p-4 text-sm leading-6">{selected.body}</div><div className="mb-5 grid grid-cols-2 gap-3 text-xs"><div><p className="text-muted-foreground">Sentiment</p><strong>{selected.sentiment}</strong></div><div><p className="text-muted-foreground">AI confidence</p><strong>94.2%</strong></div><div><p className="text-muted-foreground">Category</p><strong>{selected.category}</strong></div><div><p className="text-muted-foreground">Resolution target</p><strong>{selected.resolution}</strong></div></div><div className="space-y-2"><Button className="w-full" onClick={()=>update("Resolved (AI)")}><CheckCircle2/>Mark resolved</Button><Button variant="destructive" className="w-full" onClick={()=>update("Escalated")}><Siren/>Escalate</Button></div></div>:<div className="grid min-h-80 place-items-center text-center"><div><MailOpen className="mx-auto mb-3 size-9 text-muted-foreground"/><p className="font-semibold">Select an email</p><p className="text-sm text-muted-foreground">Open a conversation to review and act.</p></div></div>}</></Panel>
 </div></>;
}
