import { useState } from "react";
import { Area, AreaChart, CartesianGrid, Line, ResponsiveContainer, Tooltip, XAxis, YAxis, BarChart, Bar, Cell } from "recharts";
import { Mail, Bot, Gauge, Timer, Clock3, Siren, Star, Download, SlidersHorizontal, ArrowRight, CheckCircle2 } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { categories, emails, volumeData } from "@/lib/dashboard-data";
import { Donut, MetricCard, Panel, StatusPill } from "./ui";
import { useNavigate } from "@tanstack/react-router";

export function Overview() {
 const [range, setRange] = useState("week"); const navigate = useNavigate();
 const data = range === "today" ? volumeData.slice(-1) : range === "month" ? [...volumeData, ...volumeData, ...volumeData, ...volumeData].map((d,i)=>({...d,day:`W${Math.floor(i/7)+1}-${d.day}`})) : volumeData;
 const download = () => { const blob = new Blob(["Metric,Value\nEmails received,8426\nAI resolved,6214\nAutomation rate,73.7%"], { type: "text/csv" }); const url=URL.createObjectURL(blob); const a=document.createElement("a"); a.href=url;a.download="weekly-email-report.csv";a.click();URL.revokeObjectURL(url); };
 return <div className="space-y-3">
  <div className="flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-2xl font-bold">Weekly Overview</h2><p className="text-sm text-muted-foreground">Email operations at a glance</p></div><Select value={range} onValueChange={setRange}><SelectTrigger className="w-36 bg-card"><SelectValue/></SelectTrigger><SelectContent><SelectItem value="today">Today</SelectItem><SelectItem value="week">This week</SelectItem><SelectItem value="month">This month</SelectItem></SelectContent></Select></div>
  <div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4 2xl:grid-cols-7">
   <MetricCard label="Total Emails Received" value="8,426" change="12%" icon={<Mail/>}/><MetricCard label="AI Auto-Resolved" value="6,214" change="15%" icon={<Bot/>}/><MetricCard label="Automation Rate" value="73.7%" change="2.8%" icon={<Gauge/>}/><MetricCard label="First Response Time" value="36 sec" change="28%" icon={<Timer/>}/><MetricCard label="Resolution Time (Avg)" value="2h 18m" change="32%" icon={<Clock3/>}/><MetricCard label="Escalation Rate" value="8.6%" change="1.2%" positive={false} icon={<Siren/>}/><MetricCard label="Customer Satisfaction" value="4.4 / 5" change="0.2" icon={<Star/>}/>
  </div>
  <div className="grid gap-3 xl:grid-cols-[1.4fr_1fr_1fr]">
   <Panel title="Email Volume & Resolution Trend"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id="receive" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="var(--primary)" stopOpacity={.25}/><stop offset="1" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--border)" vertical={false}/><XAxis dataKey="day" tick={{fontSize:11}} axisLine={false}/><YAxis tick={{fontSize:11}} axisLine={false}/><Tooltip/><Area type="monotone" dataKey="received" stroke="var(--primary)" fill="url(#receive)" strokeWidth={2}/><Line type="monotone" dataKey="resolved" stroke="var(--success)" strokeWidth={2}/><Line type="monotone" dataKey="human" stroke="var(--destructive)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Panel>
   <Panel title="Email Processing Funnel"><div className="space-y-2">{[["Emails received",8426,"100%"],["Valid & classified",7812,"92.7%"],["Auto-resolved",6214,"73.7%"],["Human handled",1489,"17.7%"],["Escalated",724,"8.6%"]].map(([l,v,p],i)=><div key={String(l)} className="mx-auto flex h-9 items-center justify-between rounded-md px-3 text-xs font-semibold text-primary-foreground" style={{width:`${100-i*11}%`,background:`color-mix(in oklab, var(--primary) ${100-i*12}%, var(--success))`}}><span>{l}</span><strong>{Number(v).toLocaleString()} · {p}</strong></div>)}</div></Panel>
   <Panel title="Top Query Categories" action={<Button variant="ghost" size="sm" onClick={()=>navigate({to:"/service-categories"})}>View all <ArrowRight/></Button>}><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={categories} layout="vertical" margin={{left:8,right:8}}><XAxis type="number" hide/><YAxis dataKey="name" type="category" width={112} tick={{fontSize:10}} axisLine={false} tickLine={false}/><Tooltip/><Bar dataKey="value" radius={[0,3,3,0]}>{categories.map((c)=><Cell key={c.name} fill={c.color}/>)}</Bar></BarChart></ResponsiveContainer></div></Panel>
  </div>
  <div className="grid gap-3 xl:grid-cols-[1.2fr_1.2fr_1fr]">
   <Panel title="SLA Performance"><div className="grid grid-cols-2 gap-5 sm:grid-cols-4"><Donut value={96.1} label="First Response" tone="success"/><Donut value={92.4} label="Resolution"/><Donut value={91.4} label="Within Escalation" tone="warning"/><Donut value={99.6} label="No Breach" tone="success"/></div></Panel>
   <Panel title="Customer Experience"><div className="grid grid-cols-3 gap-3"><div className="rounded-md bg-success-soft p-3"><p className="text-xs text-muted-foreground">Positive</p><strong className="text-xl text-success">72%</strong></div><div className="rounded-md bg-warning-soft p-3"><p className="text-xs text-muted-foreground">Neutral</p><strong className="text-xl text-warning">21%</strong></div><div className="rounded-md bg-destructive-soft p-3"><p className="text-xs text-muted-foreground">Negative</p><strong className="text-xl text-destructive">7%</strong></div></div><div className="mt-5 space-y-3 text-sm"><div className="flex justify-between"><span>Repeat contact rate</span><strong>6.3% ↓</strong></div><div className="flex justify-between"><span>Unresolved rate</span><strong>4.9% ↓</strong></div><div className="flex justify-between"><span>CSAT trend</span><strong>4.4 / 5 ↑</strong></div></div></Panel>
   <Panel title="Quick Actions"><div className="space-y-2"><Button className="w-full justify-start" onClick={()=>navigate({to:"/email-queue"})}><Mail/>View Email Queue</Button><Button variant="outline" className="w-full justify-start" onClick={download}><Download/>Download Weekly Report</Button><Button variant="outline" className="w-full justify-start" onClick={()=>navigate({to:"/ai-performance"})}><SlidersHorizontal/>Configure AI Responses</Button></div></Panel>
  </div>
  <div className="grid gap-3 xl:grid-cols-[1.5fr_1fr]">
   <Panel title="Recent High Priority Emails" action={<Button variant="link" onClick={()=>navigate({to:"/email-queue"})}>View all</Button>}><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="text-muted-foreground"><tr className="border-b border-border">{["Received","Subject","Category","Priority","Status","Resolution"].map(h=><th className="pb-2 font-semibold" key={h}>{h}</th>)}</tr></thead><tbody>{emails.slice(0,5).map(e=><tr key={e.id} className="border-b border-border/70 last:border-0"><td className="py-2">{e.received}</td><td className="font-medium">{e.subject}</td><td>{e.category}</td><td>{e.priority}</td><td><StatusPill tone={e.status==="Escalated"?"danger":e.status==="Resolved (AI)"?"success":"warning"}>{e.status}</StatusPill></td><td>{e.resolution}</td></tr>)}</tbody></table></div></Panel>
   <Panel title="Key Insights"><ul className="space-y-3 text-sm">{["Email volume increased 12% compared to last week.","Automation improved by 2.8% after intent tuning.","Account-related queries remain the top category.","SLA breach rate remains low at 0.4%."].map(x=><li className="flex gap-2" key={x}><CheckCircle2 className="mt-0.5 size-4 shrink-0 text-success"/>{x}</li>)}</ul></Panel>
  </div>
 </div>;
}
