import { useState } from "react";
import { Area, AreaChart, Bar, BarChart, CartesianGrid, Cell, Line, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { Bot, BrainCircuit, CheckCircle2, Clock3, Download, FileBarChart, Gauge, MessageCircle, ShieldAlert, ShieldCheck, Sparkles, TrendingUp, Users, Zap } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Switch } from "@/components/ui/switch";
import { categories, volumeData } from "@/lib/dashboard-data";
import { Donut, MetricCard, PageHeading, Panel, ProgressRow, StatusPill } from "./ui";

const metadata = {
 "ai-performance": {title:"AI Performance",desc:"Accuracy, automation, and model quality",metrics:[["Intent accuracy","94.8%","1.6%"],["Automation rate","73.7%","2.8%"],["Avg confidence","91.3%","0.9%"],["Fallback rate","3.2%","0.6%"]]},
 "customer-insights": {title:"Customer Insights",desc:"Sentiment, satisfaction, and contact patterns",metrics:[["CSAT","4.4 / 5","0.2"],["Positive sentiment","72%","4.0%"],["Repeat contacts","6.3%","1.1%"],["Unique customers","5,912","8.4%"]]},
 "service-categories": {title:"Service Categories",desc:"Demand and automation by customer intent",metrics:[["Active categories","24","2 new"],["Top category","Account","25.5%"],["Best automated","KYC","86.4%"],["Needs review","Cards","8.7%"]]},
 "sla-operations": {title:"SLA & Operations",desc:"Service levels, workload, and team capacity",metrics:[["First response SLA","96.1%","1.1%"],["Resolution SLA","92.4%","2.3%"],["Hours saved","1,268","22%"],["System uptime","99.9%","0.1%"]]},
 "risk-compliance": {title:"Risk & Compliance",desc:"Escalations, policy checks, and audit readiness",metrics:[["Policy adherence","98.7%","0.8%"],["Flagged emails","47","12%"],["Critical cases","3","2 fewer"],["Audit coverage","100%","0%"]]},
} as const;

export function SectionPage({ kind }: { kind: keyof typeof metadata }) {
 const m=metadata[kind]; const [period,setPeriod]=useState("7D"); const chart=volumeData.map((d,i)=>({...d,score:Math.round(84+i*1.6+(period==="30D"?3:0)),cases:categories[i%5].value/10}));
 return <><PageHeading title={m.title} description={m.desc} actions={<div className="flex rounded-md border border-border bg-card p-1">{["7D","30D","90D"].map(x=><Button key={x} size="sm" variant={period===x?"default":"ghost"} onClick={()=>setPeriod(x)}>{x}</Button>)}</div>}/><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{m.metrics.map((x,i)=><MetricCard key={x[0]} label={x[0]} value={x[1]} change={x[2]} positive={!(x[0].includes("Fallback")||x[0].includes("Repeat")||x[0].includes("Flagged")||x[0].includes("Critical"))} icon={i===0?<Gauge/>:i===1?<TrendingUp/>:i===2?<Users/>:<Zap/>}/>)}</div>
 <div className="mt-3 grid gap-3 xl:grid-cols-[1.5fr_1fr]"><Panel title={`${m.title} trend`}><div className="h-72"><ResponsiveContainer width="100%" height="100%"><AreaChart data={chart}><defs><linearGradient id={`g-${kind}`} x1="0" y1="0" x2="0" y2="1"><stop stopColor="var(--primary)" stopOpacity={.28}/><stop offset="1" stopColor="var(--primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="day" axisLine={false}/><YAxis axisLine={false}/><Tooltip/><Area dataKey={kind==="service-categories"?"cases":"score"} stroke="var(--primary)" fill={`url(#g-${kind})`} strokeWidth={2}/><Line dataKey="resolved" stroke="var(--success)" strokeWidth={2}/></AreaChart></ResponsiveContainer></div></Panel>
 <Panel title="Performance distribution"><div className="grid grid-cols-2 gap-5"><Donut value={94.8} label="Healthy" tone="success"/><Donut value={kind==="risk-compliance"?98.7:73.7} label="On target"/></div><div className="mt-6 space-y-4">{categories.slice(0,4).map(c=><ProgressRow key={c.name} label={c.name} value={c.pct} max={30}/>)}</div></Panel></div>
 <div className="mt-3 grid gap-3 xl:grid-cols-2"><Panel title="Detailed breakdown"><div className="h-64"><ResponsiveContainer width="100%" height="100%"><BarChart data={categories}><CartesianGrid vertical={false} stroke="var(--border)"/><XAxis dataKey="name" tick={{fontSize:10}} axisLine={false}/><YAxis axisLine={false}/><Tooltip/><Bar dataKey="value" radius={[3,3,0,0]}>{categories.map(c=><Cell fill={c.color} key={c.name}/>)}</Bar></BarChart></ResponsiveContainer></div></Panel><Panel title="Recommended actions"><div className="space-y-3">{["Review the highest-volume intent for response consistency.","Inspect low-confidence replies before the next model refresh.","Share the weekly quality sample with the operations lead.","Continue monitoring outliers against the service target."].map((x,i)=><div key={x} className="flex items-start gap-3 rounded-md border border-border p-3"><div className="grid size-8 shrink-0 place-items-center rounded-md bg-primary-soft text-primary">{i===0?<BrainCircuit/>:i===1?<ShieldAlert/>:i===2?<MessageCircle/>:<Sparkles/>}</div><div><p className="text-sm font-semibold">{x}</p><p className="text-xs text-muted-foreground">Suggested from this period's sample data.</p></div><CheckCircle2 className="ml-auto size-4 text-success"/></div>)}</div></Panel></div></>;
}

export function ReportsPage(){const [done,setDone]=useState("");const reports=["Weekly Operations Summary","AI Quality & Accuracy","Customer Experience Digest","Risk and Compliance Audit","Category Volume Detail"];
 const download=(name:string)=>{const blob=new Blob([`Aarohan Bank,${name}\nGenerated,28 Sep 2026\nStatus,Sample data`],{type:"text/csv"});const u=URL.createObjectURL(blob);const a=document.createElement("a");a.href=u;a.download=`${name.toLowerCase().replaceAll(" ","-")}.csv`;a.click();URL.revokeObjectURL(u);setDone(name)};
 return <><PageHeading title="Reports" description="Downloadable operational summaries built from sample data"/><div className="grid gap-3 md:grid-cols-2 xl:grid-cols-3">{reports.map((r,i)=><div key={r} className="rounded-md border border-border bg-card p-5 shadow-panel"><div className="grid size-10 place-items-center rounded-md bg-primary-soft text-primary"><FileBarChart/></div><h3 className="mt-4 font-display text-base font-bold">{r}</h3><p className="mt-1 text-sm text-muted-foreground">Updated 28 Sep 2026 · {i%2?"CSV":"PDF / CSV"}</p><div className="mt-5 flex items-center justify-between"><StatusPill tone="success">Ready</StatusPill><Button variant="outline" size="sm" onClick={()=>download(r)}><Download/>Download</Button></div></div>)}</div>{done&&<div className="fixed bottom-5 right-5 rounded-md bg-foreground px-4 py-3 text-sm text-background shadow-lg">Downloaded {done}</div>}</>}

export function SettingsPage(){const [settings,setSettings]=useState({auto:true,escalate:true,sentiment:true,digest:false,audit:true});const toggle=(k:keyof typeof settings)=>setSettings(v=>({...v,[k]:!v[k]}));return <><PageHeading title="Settings" description="Control response automation and team notifications" actions={<Button onClick={()=>alert("Settings saved for this demo.")}>Save changes</Button>}/><div className="grid gap-3 xl:grid-cols-2"><Panel title="AI response controls"><div className="space-y-1">{[["auto","Automatic replies","Allow high-confidence replies to send automatically."],["escalate","Smart escalation","Route high-risk or low-confidence emails to an agent."],["sentiment","Sentiment detection","Detect frustration and prioritize sensitive conversations."]].map(([k,t,d])=><Setting key={k} title={t} desc={d} checked={settings[k as keyof typeof settings]} onChange={()=>toggle(k as keyof typeof settings)}/>)}</div></Panel><Panel title="Notifications & governance"><div className="space-y-1">{[["digest","Daily email digest","Send managers a daily performance summary."],["audit","Full audit trail","Keep decision logs for all AI-generated responses."]].map(([k,t,d])=><Setting key={k} title={t} desc={d} checked={settings[k as keyof typeof settings]} onChange={()=>toggle(k as keyof typeof settings)}/>)}</div></Panel></div><div className="mt-3"><Panel title="AI confidence threshold"><p className="text-sm text-muted-foreground">Responses under this score are sent for human review.</p><div className="mt-5 flex items-center gap-4"><input type="range" min="60" max="99" defaultValue="88" className="w-full accent-primary"/><strong>88%</strong></div></Panel></div></>}
function Setting({title,desc,checked,onChange}:{title:string;desc:string;checked:boolean;onChange:()=>void}){return <div className="flex items-center justify-between gap-4 border-b border-border py-4 last:border-0"><div><p className="text-sm font-semibold">{title}</p><p className="text-xs text-muted-foreground">{desc}</p></div><Switch checked={checked} onCheckedChange={onChange}/></div>}
